### ISSUE TITLE
posthog.getAll not working

### ISSUE THREAD

**Issue by SebTVisage** [PostHog/posthog-node#77]
I'm using posthog-node 2.0.2 and I get the following error when calling `getAll`:

```
stack=TypeError: undici__default.default.fetch is not a function
api                      |     at PostHogClient.fetch (/node_app/back/api/node_modules/@visage/visage-server-common/node_modules/posthog-node/src/posthog-node.ts:53:19)
api                      |     at /node_app/back/api/node_modules/@visage/visage-server-common/node_modules/posthog-core/src/index.ts:647:33
api                      |     at /node_app/back/api/node_modules/@visage/visage-server-common/node_modules/posthog-core/src/utils.ts:23:25
api                      |     at step (/node_app/back/api/node_modules/@visage/visage-server-common/node_modules/node_modules/tslib/tslib.es6.js:102:23)
api                      |     at Object.next (/node_app/back/api/node_modules/@visage/visage-server-common/node_modules/node_modules/tslib/tslib.es6.js:83:53)
api                      |     at fulfilled (/node_app/back/api/node_modules/@visage/visage-server-common/node_modules/node_modules/tslib/tslib.es6.js:73:58)
```

**Comment by neilkakkar** [comment]
Hey @SebTVisage , what's `getAll` ?

**Comment by SebTVisage** [comment]
Ok actually it's the same with `isFeatureEnabled`.

Sorry I meant `getAllFlags` (mentioned in the [docs](getAllFlags))

**Comment by neilkakkar** [comment]
Hmm, just tested the library again, I don't face the same.

How're you using the library? Some reproduction instructions would be nice.

**Comment by SebTVisage** [comment]
On a node 12 project using TS. I'll try to give you a reproduction repo. I do this more or less:
```
import { PostHog } from 'posthog-node';
import config from '../config';

export const postHogClient = new PostHog(config.thirdParties.posthog.apiKey, {
  personalApiKey: config.thirdParties.posthog.personalKey,
});

// In another file:
import { postHogClient } from '<path to file above>';
// In a function I do just something like this
const featureFlags = await postHogClient.getAllFlags('some-user-id');
```

I'll try to do a reproduction repo

**Comment by neilkakkar** [comment]
For a quick check, we're using node 16, try if that works? Might mean we need to update the supported node versions 🤔
