### ISSUE TITLE
AbortSignal is not defined

### ISSUE THREAD

**Issue by MooseSaeed** [PostHog/posthog-node#82]
I'm using Posthog node client in the backend of Nuxtjs app and I'm getting these errors in the console.

```
ERROR  AbortSignal is not defined                                                                                02:55:25

  at PostHogClient.<anonymous> (server.js:1570:17)
  at step (server.js:436:27)
  at Object.next (server.js:385:53)
  at server.js:378:71
  at new Promise (<anonymous>)
  at __awaiter (server.js:364:12)
  at PostHogClient.module.exports.../manifold/node_modules/posthog-node/lib/index.cjs.js.PostHogCore.fetchWithRetry (server.js:1567:16)
  at PostHogClient.<anonymous> (server.js:1314:52)
  at step (server.js:436:27)
  at Object.next (server.js:385:53)
```

It's a simple `getAllFlags()` attempt that successfully returns the flags values on page load. The problem is that I keep getting the above error on each page refresh.

**Comment by neilkakkar** [comment]
Hey @MooseSaeed it sounds like you're on node 14-,  while AbortSignal is defined only in node 15+. I'll update the package node requirements 👀

**Comment by MooseSaeed** [comment]
@neilkakkar Thanks for responding. I have upgraded node version to 16.13.1 and I'm still getting the error.

**Comment by neilkakkar** [comment]
Is it exactly the same error, or is it somewhat different? Mind removing and installing `posthog-node` from scratch to see if it persists?

**Comment by MooseSaeed** [comment]
@neilkakkar No matter what I try, I get the same same error. I uninstalled and reinstalled `posthog-node` and I even cleaned out my lock file, but nothing appears to work for some reason.
On the frontend, I'm using the javascript client, which works well, however the node client continues throwing these errors.

**Comment by Ruegen** [comment]
if you have an outdated version of node this polyfill worked for us until we got the update done
https://www.npmjs.com/package/abort-controller

**Comment by StockBet** [comment]
so this issue has been open for almost 1 year... yet it is still not fixed? c'mon guys @posthog-bot

**Comment by neilkakkar** [comment]
@StockBet do you have a reproducible example I can try out? I'm failing to reproduce this on node 15+

**Comment by StockBet** [comment]
What do you mean? How can I give you a reproducible example? my node is v20.4.0

Sent via Superhuman ( ***@***.*** )

**Comment by neilkakkar** [comment]
A simple project setup where it doesn't work - node + posthog installation - a github repo link works :) - pretty hard to debug if I can't tell what might be going wrong

**Comment by StockBet** [comment]
I finally figured out the issue. @neilkakkar 

Turns out Render (which I use to deploy my node server) uses 14.17.0 by default for some reason.
